### ISSUE TITLE
Remove project structure requirements/assumptions

### ISSUE THREAD

**Issue by gabe-l-hart** [caikit/caikit#30]
## Is your feature request related to a problem? Please describe.

Currently, there are several places in the code that make assumptions about the directory/module structure for the derived library. We should identify these areas and make them more generic to allow arbitrary project structures.

## Describe the solution you'd like

- [x] Identify all places where module structure assumptions are made
- [x] Fix them!

**Comment by joerunde** [comment]
@gabe-l-hart @tharapalanivel @prashantgupta24 So I think everything left for this issue is covered by #90 _except_ for the training RPC names. Right now those smash the whole directory structure for a module together to create a unique rpc name.

We may actually want an option to keep that around for backwards compatibility reasons, but we should probably also think of a better way to have unique training RPC names that aren't as verbose and don't break if you move a module to a different file.

Thoughts on repurposing this story for that specific problem?

**Comment by joerunde** [comment]
@evaline-ju is auditing right now, but we should be extremely close, if not done with this

**Comment by joerunde** [comment]
Closing as "very likely completed"
